name: Hello
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Hello
      run: echo Hello, world!
    - name: Tree
      run: |
        tree
    - name: branch_name
      run: |
        echo ${{ github.head_ref }}
    - name: repository_name
      run: echo ${{ github.repository }}
    - name: event
      run: echo event -> ${{ github.event }}
