name: Hello
on: push
env:
  foo: bar
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FOO: baz
      ACTOR: ${{ github.actor }}
      REPOSITORY: ${{ github.repository }}
      EVENT_NAME: ${{ github.event_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Hello
        run: echo Hello, world!
      - name: Tree
        run: |
          tree
      - name: Actor
        run: |
          echo "${{ env.ACTOR }}"
      - name: Repository Name
        run: echo "${{ env.REPOSITORY }}"
      - name: Event Name
        run: echo event -> "${{ env.EVENT_NAME }}"
      - name: Env Override
        run: echo foo -> "${{ env.FOO }}"
        env:
          FOO: fiz
      - name: Format String
        run: echo "${{ format('{0} {1}-san', env.LAST_NAME, env.FIRST_NAME) }}"
        env:
          FIRST_NAME: Sota
          LAST_NAME: Suzuki
