name: Hello
on: push
env:
  foo: bar
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      foo: baz
    steps:
    - uses: actions/checkout@v4
    - name: Hello
      run: echo Hello, world!
    - name: Tree
      run: |
        tree
    - name: actor
      run: |
        echo ${{ github.actor }}
    - name: repository_name
      run: echo ${{ github.repository }}
    - name: event_name
      run: echo event -> ${{ github.event_name }}
    - name: check env override
      run: echo foo -> ${{ env.foo }}
      env:
        foo: fiz
