name: Hello
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Hello
      run: echo Hello, world!
    - name: Tree
      run: |
        tree
    - name: actor
      run: |
        echo ${{ github.actor }}
    - name: repository_name
      run: echo ${{ github.repository }}
    - name: event_name
      run: echo event -> ${{ github.event_name }}
