name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: "Hello"
        required: true
        description: "Greeting message"
      log_level:
        type: choice
        default: "info"
        options:
          - "debug"
          - "info"
          - "warning"
          - "error"
        description: "Select log level"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Message
        run: echo ${{ inputs.greeting }}
      - name: Log level
        run: echo Log level -> ${{ inputs.log_level }}
